version: "3"
services:
  frontend:
    build: ./frontend
    image: frontend
    links:
      - backend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    image: backend
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8000:8000"
    environment:
      MONGO_DB: ${MONGO_DB}
      SECRET: ${SECRET}
  mongo:
    image: mongo
    ports:
      - "27107:27107"
